Update files to java 14
andrea-sanchez/color-generator pull request #8
Opened 2020-09-15 22:48 UTC by efren-cabrera

Update Java version

2020-09-18 16:33 UTC, JoseeCosio commented on pom.xml
> +		<java.version>1.14</java.version>
Recordar que a partir de java 9, la versión utiliza el formato: 9, 10, 11, 12... etc.

2020-09-18 17:23 UTC, efren-cabrera commented on pom.xml
> +		<java.version>1.14</java.version>
Si, esto lo resolví en el siguiente pr, si lo cambio aquí se van a generar conflictos

2020-09-18 17:26 UTC, JoseeCosio commented
Es confuso que distintos prs traten de añadir el mismo código. Tal vez sea
mejor práctica encapsularlos en distintas ramas.

El vie., 18 de septiembre de 2020 10:24 a. m., Jesus Efren Cabrera Ortega <
notifications@github.com> escribió:

> @efren-cabrera <https://github.com/efren-cabrera> requested your review
> on: #8 <https://github.com/andrea-sanchez/color_generator/pull/8> Update
> files to java 14.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/andrea-sanchez/color_generator/pull/8#event-3783564671>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN2H5ZNMRQIYDY2F372H4T3SGOJULANCNFSM4RN4H2OA>
> .
>

2020-09-18 17:38 UTC, efren-cabrera commented
Si @JoseeCosio, es que creo que viven demasiado tiempo los pr, pero en el de las pruebas necesitaba tener la nueva versión de java, porque si cambia un poco la forma de hacerlas, se "deprecan" varias cosas.

2020-09-19 04:47 UTC, andrea-sanchez approved these changes

2020-09-19 04:50 UTC, andrea-sanchez commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Tal vez sea buena idea cambiar la variable `r`, después de aprobar este PR, por un nombre mas descriptivo

2020-09-19 04:50 UTC, andrea-sanchez commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
lo escribo para que no se me olvide jajaja

2020-09-19 04:51 UTC, efren-cabrera commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Si, podrías ponerlo en un issue

2020-09-19 05:01 UTC, JoseeCosio commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Puedes hacer request changes, creo que deberías para no volver a checarlo después.

2020-09-19 05:02 UTC, JoseeCosio commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
@andrea-sanchez

2020-09-19 05:04 UTC, efren-cabrera commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Pero creo que ella tiene una rama donde está cambiando los nombres, me suena mejor que lo haga allá ¿No?

2020-09-19 05:05 UTC, JoseeCosio requested changes
Favor de cambiar nombre de variable r por algo descriptivo.
Línea 12 de RandomColorGenerator.

2020-09-19 05:05 UTC, JoseeCosio commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Favor de cambiar nombre de variable r por algo descriptivo.

2020-09-19 05:08 UTC, andrea-sanchez commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
así es @efren-cabrera tengo una rama y un issue ya con esto, lo agrego

2020-09-19 05:08 UTC, JoseeCosio commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Deberían de jalar los cambios si les ganan el PR, según entiendo, no?

2020-09-19 05:10 UTC, efren-cabrera commented on src/main/java/dev/kodice/hexcolorgenerator/services/RandomColorGenerator.java
> +		var r = Optional.ofNullable(random).orElse(new Random());
Es que no se ha aceptado ninguno de los dos, siguen abiertos ambos PR, pero ya hice el cambio, que ella batallé con los conflictos.

2020-09-19 05:12 UTC, JoseeCosio approved these changes

2020-09-19 05:18 UTC, merged